name: lawyer_app
description: "一个律师的AI智能项目"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.3

  #网络
  dio: ^5.9.0
  #日志打印
  pretty_dio_logger: ^1.4.0
  #网络监听
  connectivity_plus: ^7.0.0
  #网络图片加载
  cached_network_image: ^3.4.1
  #屏幕适配工具
  flutter_screenutil: ^5.9.3
  #简单数据存储
  shared_preferences: ^2.5.3
  #下拉上拉刷新
  pull_to_refresh: ^2.0.0
  #loading
  flutter_easyloading: ^3.0.5
  #toast
  fluttertoast: ^9.0.0
  #包信息
  package_info_plus: ^9.0.0
  #文件管理
  path_provider: ^2.1.5
  #设备信息
  device_info_plus: ^12.3.0
  #轮播图
  card_swiper: ^3.0.1
  #打开链接
  url_launcher: ^6.3.2
  app_links: ^6.4.1
  #权限工具
  permission_handler: ^12.0.1
  decimal: ^3.2.4
  #图片选择
  image_picker: ^1.2.1
  wechat_assets_picker: ^10.0.0
  #webview
  flutter_inappwebview: ^6.1.5
  #二维码生成
  qr_flutter: ^4.1.0
  #图片assets管理
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.10.4
  #图片保存
  image_gallery_saver_plus: ^4.0.1
  #图片裁剪
  croppy: ^1.4.1
  #图片压缩
  flutter_image_compress: ^2.4.0
  #html
  flutter_html: ^3.0.0
  #app更新提醒框
  flutter_app_update: ^3.2.2
  #个推
  getuiflut: ^0.2.39
  #本地通知
  flutter_local_notifications: ^19.5.0
  #图片浏览
  photo_view: ^0.14.0
  #键盘和工具栏切换
  chat_bottom_container: ^0.4.0
  #ai文字逐字回答UI
  typewritertext: ^3.0.9
  #语音转文字
  speech_to_text: ^7.3.0
  #录音
  record: ^6.1.2
  #配置appicon
  flutter_launcher_icons: ^0.14.4
  #启动图
  flutter_native_splash: ^2.4.7
  #配置名字
  launcher_name: ^1.0.2
  #国际化
  intl: ^0.19.0
  flutter_cupertino_datetime_picker2: ^3.0.2
  #震动反馈
  vibration: ^3.1.5
  #日历
  flutter_advanced_calendar:
    path: plugins/flutter_advanced_calendar-1.4.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/common/
    - assets/tabbar/
    - assets/home/
    - assets/my/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/common/app_logo.png"
  adaptive_icon_background: "#ffffff"  # 自适应图标背景色（白色）
  adaptive_icon_foreground: "assets/common/app_logo.png"  # 自适应图标前景

flutter_native_splash:
  color: "#ffffff"  # 背景颜色
  image: assets/common/launch_img.png
  android: true
  ios: true
  android_gravity: "fill"
  ios_content_mode: "scaleAspectFill"

launcher_name:
  default: "灵动"

#更新 dart run flutter_native_splash:create
# dart run flutter_launcher_icons
#dart run launcher_name:main